locale: "en-US"
title: "Can Luo's homepage"
name: "Can Luo"
description: "Postdoctoral researcher at the University of Washington"
url: "https://volcano1998.github.io"
baseurl: ""
repository: "volcano1998/volcano1998.github.io"
remote_theme: "academicpages/academicpages.github.io"
plugins:
  - jekyll-remote-theme

author:
  name: "Can Luo"
  avatar: "can-luo.jpg"
  bio: "Postdoctoral Researcher at the University of Washington"
  location: "Seattle, Washington"
  email: "canl98@uw.edu"
  github: "volcano1998"
  googlescholar: "https://scholar.google.com/citations?user=2oxA4e8AAAAJ&hl=en"
  linkedin: "can-luo-935b11186"

include:
  - _pages

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
markdown: kramdown
kramdown:
  input: GFM
